### ISSUE TITLE
Minor Error: Some Stacktrace...

### ISSUE THREAD

**Issue by chuushi** [talrey/ArcaneChatUtils#38]
```
[22:29:24 ERROR] [net.dv8tion.jda.core.requests.RestAction]: Encountered error while processing success consumer
java.lang.IllegalStateException: Preventing use of complete() in callback threads! This operation can be a deadlock cause
        at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:429) ~[?:?]
        at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:399) ~[?:?]
        at com.arcaneminecraft.bungee.channel.discord.DiscordListener.lambda$onGuildMessageReceived$0(DiscordListener.java:95) ~[?:?]
        at net.dv8tion.jda.core.requests.Request.lambda$onSuccess$0(Request.java:77) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_171]
```

**Comment by chuushi** [comment]
The code block in question is:

```java
            if (uuid == null) {
                e.getMessage().delete().complete();
                // Send message saying to register discord to mc account
                user.openPrivateChannel().queue(channel ->
                        channel
                                .sendMessage(":x: Your message in \\#"
                                        + mcChatChannel.getName()
                                        + " was deleted because your account is not linked. Run `"
                                        + getPrefix()
                                        + "link"
                                        + "` to get started!")
                                .complete()); // <<==== HERE
                return;
            }
```

I don't know how to fix this easily; I'll have to look into how RestAction works to fix this...
